### ISSUE TITLE
The snap file isn't in squashfs format

### ISSUE THREAD

**Issue by mumblee** [emilyastranova/authy-snapless#2]
Hello,

I have an error with the script.
After downloading the snap file, the unsquashfs command fails to extract it. Here is the error message :

> Extracting snap file...
> FATAL ERROR: Can't find a valid SQUASHFS superblock on H8ZpNgIoPyvmkgxOWw5MSzsXK1wRZiHn_12.snap

This happens with squashfs-tools 1:4.5.1-1

My Debian 12.5 was not up to date. I'm currently upgrading to give the script a new try but I am not too optimistic...

Any idea ?

**Comment by mumblee** [comment]
Update : same behavior with an up to date Debian 12.5.
Besides, the snap file called "H8ZpNgIoPyvmkgxOWw5MSzsXK1wRZiHn" in the script is downloaded without error but its size is only 205 bytes. This seems really small...

**Comment by adil192** [comment]
Authy got removed from the snap store so the download link doesn't work. You can download it manually from the [Wayback Machine](https://web.archive.org/web/20231121013806/https://api.snapcraft.io/api/v1/snaps/download/H8ZpNgIoPyvmkgxOWw5MSzsXK1wRZiHn_21.snap) (source: [this gist](https://gist.github.com/ruario/46c528b01581e22e07f06c451914ada9?permalink_comment_id=5067818#gistcomment-5067818)) but it's no longer working in 2024 with a "minimum integrity requirements" error.

**Comment by emilyastranova** [comment]
It looks like Authy Desktop is dead now :(
Closing this issue and archiving repo
